import {
  LOCAL_BASE_URL_ANDROID,
  LOCAL_BASE_URL_IOS,
  PRD_BASE_URL,
  DEV_STRIPE_PUBLISH_KEY,
  PRD_STRIPE_PUBLISH_KEY,
  DEV_ONESIGNAL_APP_ID,
  PRD_ONESIGNAL_APP_ID,
} from '@env';
import {Platform} from 'react-native';

const LOCAL_BASE_URL =
  Platform.OS === 'android' ? LOCAL_BASE_URL_ANDROID : LOCAL_BASE_URL_IOS;

export const BASE_URL = __DEV__ ? LOCAL_BASE_URL : PRD_BASE_URL;
export const STRIPE_PUBLISH_KEY = __DEV__
  ? DEV_STRIPE_PUBLISH_KEY
  : PRD_STRIPE_PUBLISH_KEY;

export const ONESIGNAL_APP_ID = __DEV__
  ? DEV_ONESIGNAL_APP_ID
  : PRD_ONESIGNAL_APP_ID;
